name: java CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Get the code in remote server
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Execute jar file
        run: |
          # Find and kill the existing Java process
          existing_pid=$(sudo lsof -t -i:8080 || true)  # Change 8080 to your application's port
          if [ ! -z "$existing_pid" ]; then
            echo "Stopping existing instance of the application..."
            sudo kill -9 $existing_pid
          fi
          sudo java -jar /home/ubuntu/actions-runner/_work/spring-boot-public-and-private-chat/spring-boot-public-and-private-chat/target/learn-websocket-0.0.1-SNAPSHOT.jar
          exit
          EOF